### ISSUE TITLE
feature request: use line 4 of sign to indicate marker set

### ISSUE THREAD

**Issue by drakmirv** [theAspenGrove/BlueMap-Signs#12]
It would be good to be able to segregate markers created into multiple sets (houses, dungeons, etc.) based on the sign contents.

**Comment by mov51** [comment]
I'm not using the 4th line of the sign for anything right now, so that sounds like a good place for it to be. It should be easy enough to implement too :D

**Comment by mov51** [comment]
I've got most of the work done on this! It was a bit more complicated than I thought but I only need to do some cleanup now :D 
![2021-06-28_04 11 46](https://user-images.githubusercontent.com/16448318/123602937-520d5000-d7c7-11eb-93c8-dd4e27f48011.png)
![MOV-2021-06-28__7434](https://user-images.githubusercontent.com/16448318/123602956-58033100-d7c7-11eb-81a2-9f19d670202e.png)

**Comment by drakmirv** [comment]
Neat!  Didn't expect it so quickly, great job!

**Comment by mov51** [comment]
added in [1.3](https://github.com/theAspenGrove/BlueMap-Signs/releases/tag/1.3)!

**Comment by drakmirv** [comment]
Awesome, I'll install it today.  :)
